insert into ORDENES (DETALLE) values ('Pepper - Chili Powder');
insert into ORDENES (DETALLE) values ('Jameson Irish Whiskey');
insert into ORDENES (DETALLE) values ('Tea - Apple Green Tea');
insert into ORDENES (DETALLE) values ('Muffin - Mix - Strawberry Rhubarb');
insert into ORDENES (DETALLE) values ('Maple Syrup');
insert into ORDENES (DETALLE) values ('Pork - Sausage Casing');
insert into ORDENES (DETALLE) values ('Nantuket Peach Orange');
insert into ORDENES (DETALLE) values ('Wine - Kwv Chenin Blanc South');
insert into ORDENES (DETALLE) values ('Wine - Sogrape Mateus Rose');
insert into ORDENES (DETALLE) values ('Red Currant Jelly');
insert into ORDENES (DETALLE) values ('Seedlings - Mix, Organic');
insert into ORDENES (DETALLE) values ('Pear - Packum');
insert into ORDENES (DETALLE) values ('Lemon Tarts');
insert into ORDENES (DETALLE) values ('Duck - Fat');
insert into ORDENES (DETALLE) values ('Bread - Pullman, Sliced');
insert into ORDENES (DETALLE) values ('Spinach - Packaged');
insert into ORDENES (DETALLE) values ('Sugar - Brown, Individual');
insert into ORDENES (DETALLE) values ('Cabbage - Nappa');
insert into ORDENES (DETALLE) values ('Nacho Chips');
insert into ORDENES (DETALLE) values ('Lettuce - Red Leaf');
insert into ORDENES (DETALLE) values ('Kellogs All Bran Bars');
insert into ORDENES (DETALLE) values ('Beef - Top Butt');
insert into ORDENES (DETALLE) values ('Pork - Smoked Back Bacon');
insert into ORDENES (DETALLE) values ('White Fish - Filets');
insert into ORDENES (DETALLE) values ('Pear - Prickly');
insert into ORDENES (DETALLE) values ('Tea - Decaf Lipton');
insert into ORDENES (DETALLE) values ('Mushroom - Morel Frozen');
insert into ORDENES (DETALLE) values ('Sobe - Cranberry Grapefruit');
insert into ORDENES (DETALLE) values ('Wine - Dubouef Macon - Villages');
insert into ORDENES (DETALLE) values ('Beef - Ground Lean Fresh');
insert into ORDENES (DETALLE) values ('Pork - Loin, Bone - In');
insert into ORDENES (DETALLE) values ('Soup - Base Broth Beef');
insert into ORDENES (DETALLE) values ('Duck - Fat');
insert into ORDENES (DETALLE) values ('Flower - Commercial Spider');
insert into ORDENES (DETALLE) values ('Sprouts - Bean');
insert into ORDENES (DETALLE) values ('Tomatoes - Vine Ripe, Red');
insert into ORDENES (DETALLE) values ('Gatorade - Lemon Lime');
insert into ORDENES (DETALLE) values ('Coffee - French Vanilla Frothy');
insert into ORDENES (DETALLE) values ('Turkey Leg With Drum And Thigh');
insert into ORDENES (DETALLE) values ('Yogurt - Assorted Pack');
insert into ORDENES (DETALLE) values ('Nut - Peanut, Roasted');
insert into ORDENES (DETALLE) values ('Nectarines');
insert into ORDENES (DETALLE) values ('Flour - Bran, Red');
insert into ORDENES (DETALLE) values ('Cape Capensis - Fillet');
insert into ORDENES (DETALLE) values ('Table Cloth 91x91 Colour');
insert into ORDENES (DETALLE) values ('Cookies - Amaretto');
insert into ORDENES (DETALLE) values ('Miso Paste White');
insert into ORDENES (DETALLE) values ('Pork - Loin, Bone - In');
insert into ORDENES (DETALLE) values ('Bread - Onion Focaccia');
insert into ORDENES (DETALLE) values ('Lamb - Leg, Bone In');
insert into ORDENES (DETALLE) values ('Thyme - Lemon, Fresh');
insert into ORDENES (DETALLE) values ('Anchovy Fillets');
insert into ORDENES (DETALLE) values ('Onions Granulated');
insert into ORDENES (DETALLE) values ('Pepper - Green Thai');
insert into ORDENES (DETALLE) values ('Broccoli - Fresh');
insert into ORDENES (DETALLE) values ('Pasta - Orzo, Dry');
insert into ORDENES (DETALLE) values ('Salmon - Smoked, Sliced');
insert into ORDENES (DETALLE) values ('Beer - Guiness');
insert into ORDENES (DETALLE) values ('Wine La Vielle Ferme Cote Du');
insert into ORDENES (DETALLE) values ('True - Vue Containers');
insert into ORDENES (DETALLE) values ('Wine - Prosecco Valdobienne');
insert into ORDENES (DETALLE) values ('Soup - Campbells Mushroom');
insert into ORDENES (DETALLE) values ('Soup - Campbells Beef Noodle');
insert into ORDENES (DETALLE) values ('Oil - Shortening - All - Purpose');
insert into ORDENES (DETALLE) values ('Pork - Smoked Back Bacon');
insert into ORDENES (DETALLE) values ('Apples - Spartan');
insert into ORDENES (DETALLE) values ('Mackerel Whole Fresh');
insert into ORDENES (DETALLE) values ('Oven Mitts - 15 Inch');
insert into ORDENES (DETALLE) values ('Oil - Hazelnut');
insert into ORDENES (DETALLE) values ('Yoghurt Tubes');
insert into ORDENES (DETALLE) values ('Bagel - Ched Chs Presliced');
insert into ORDENES (DETALLE) values ('Herb Du Provence - Primerba');
insert into ORDENES (DETALLE) values ('Table Cloth 62x114 Colour');
insert into ORDENES (DETALLE) values ('Gherkin');
insert into ORDENES (DETALLE) values ('Appetizer - Southwestern');
insert into ORDENES (DETALLE) values ('Bread - Sour Sticks With Onion');
insert into ORDENES (DETALLE) values ('Yokaline');
insert into ORDENES (DETALLE) values ('Juice - Apple, 341 Ml');
insert into ORDENES (DETALLE) values ('Jolt Cola');
insert into ORDENES (DETALLE) values ('Wine - Beringer Founders Estate');
insert into ORDENES (DETALLE) values ('Tortillas - Flour, 10');
insert into ORDENES (DETALLE) values ('Lamb - Leg, Bone In');
insert into ORDENES (DETALLE) values ('Wine - Red, Black Opal Shiraz');
insert into ORDENES (DETALLE) values ('Salt - Sea');
insert into ORDENES (DETALLE) values ('Latex Rubber Gloves Size 9');
insert into ORDENES (DETALLE) values ('Lettuce - Boston Bib - Organic');
insert into ORDENES (DETALLE) values ('Apron');
insert into ORDENES (DETALLE) values ('Wine - Blue Nun Qualitatswein');
insert into ORDENES (DETALLE) values ('Beer - Guiness');
insert into ORDENES (DETALLE) values ('Water Chestnut - Canned');
insert into ORDENES (DETALLE) values ('Bag Stand');
insert into ORDENES (DETALLE) values ('Cookie Dough - Chunky');
insert into ORDENES (DETALLE) values ('Oil - Olive');
insert into ORDENES (DETALLE) values ('Potatoes - Mini Red');
insert into ORDENES (DETALLE) values ('Stainless Steel Cleaner Vision');
insert into ORDENES (DETALLE) values ('Yogurt - Blueberry, 175 Gr');
insert into ORDENES (DETALLE) values ('Versatainer Nc - 9388');
insert into ORDENES (DETALLE) values ('Sausage - Breakfast');
insert into ORDENES (DETALLE) values ('Flower - Potmums');
insert into ORDENES (DETALLE) values ('Cheese - Gouda Smoked');
insert into ORDENES (DETALLE) values ('Pickles - Gherkins');
insert into ORDENES (DETALLE) values ('Ginger - Fresh');
insert into ORDENES (DETALLE) values ('Steampan - Half Size Shallow');
insert into ORDENES (DETALLE) values ('Soup - Campbells, Creamy');
insert into ORDENES (DETALLE) values ('Strawberries - California');
insert into ORDENES (DETALLE) values ('Wine - Montecillo Rioja Crianza');
insert into ORDENES (DETALLE) values ('Trout - Smoked');
insert into ORDENES (DETALLE) values ('Olives - Kalamata');
insert into ORDENES (DETALLE) values ('Nutmeg - Ground');
insert into ORDENES (DETALLE) values ('Wine - Placido Pinot Grigo');
insert into ORDENES (DETALLE) values ('Daikon Radish');
insert into ORDENES (DETALLE) values ('Calypso - Pineapple Passion');
insert into ORDENES (DETALLE) values ('Wiberg Super Cure');
insert into ORDENES (DETALLE) values ('Bread - White, Unsliced');
insert into ORDENES (DETALLE) values ('Wine - White, Cooking');
insert into ORDENES (DETALLE) values ('Ecolab - Ster Bac');
insert into ORDENES (DETALLE) values ('Pork - Tenderloin, Frozen');
insert into ORDENES (DETALLE) values ('Bagel - Whole White Sesame');
insert into ORDENES (DETALLE) values ('Coke - Classic, 355 Ml');
insert into ORDENES (DETALLE) values ('Wine - Zinfandel Rosenblum');
insert into ORDENES (DETALLE) values ('Wine - Cotes Du Rhone');
insert into ORDENES (DETALLE) values ('Nut - Macadamia');
insert into ORDENES (DETALLE) values ('Tart - Lemon');
insert into ORDENES (DETALLE) values ('Sauce - Vodka Blush');
insert into ORDENES (DETALLE) values ('Haggis');
insert into ORDENES (DETALLE) values ('Milk 2% 500 Ml');
insert into ORDENES (DETALLE) values ('Vinegar - Sherry');
insert into ORDENES (DETALLE) values ('Beans - Fava, Canned');
insert into ORDENES (DETALLE) values ('Ranchero - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Danishes - Mini Raspberry');
insert into ORDENES (DETALLE) values ('Cheese - Cheddar, Medium');
insert into ORDENES (DETALLE) values ('Daikon Radish');
insert into ORDENES (DETALLE) values ('Bananas');
insert into ORDENES (DETALLE) values ('Beef - Tender Tips');
insert into ORDENES (DETALLE) values ('Sprite - 355 Ml');
insert into ORDENES (DETALLE) values ('Horseradish - Prepared');
insert into ORDENES (DETALLE) values ('Curry Paste - Madras');
insert into ORDENES (DETALLE) values ('Soup V8 Roasted Red Pepper');
insert into ORDENES (DETALLE) values ('Cheese - Mix');
insert into ORDENES (DETALLE) values ('Cake - French Pear Tart');
insert into ORDENES (DETALLE) values ('Roe - Lump Fish, Black');
insert into ORDENES (DETALLE) values ('Pasta - Spaghetti, Dry');
insert into ORDENES (DETALLE) values ('Cheese - Wine');
insert into ORDENES (DETALLE) values ('Juice - Tomato, 48 Oz');
insert into ORDENES (DETALLE) values ('Thermometer Digital');
insert into ORDENES (DETALLE) values ('Bread - French Stick');
insert into ORDENES (DETALLE) values ('Corn - On The Cob');
insert into ORDENES (DETALLE) values ('Wine - Spumante Bambino White');
insert into ORDENES (DETALLE) values ('Coffee - 10oz Cup 92961');
insert into ORDENES (DETALLE) values ('Cocoa Feuilletine');
insert into ORDENES (DETALLE) values ('Lambcasing');
insert into ORDENES (DETALLE) values ('Beans - Yellow');
insert into ORDENES (DETALLE) values ('Pear - Halves');
insert into ORDENES (DETALLE) values ('Salmon - Fillets');
insert into ORDENES (DETALLE) values ('Veal - Nuckle');
insert into ORDENES (DETALLE) values ('Peach - Halves');
insert into ORDENES (DETALLE) values ('Southern Comfort');
insert into ORDENES (DETALLE) values ('Banana');
insert into ORDENES (DETALLE) values ('Pork - Tenderloin, Fresh');
insert into ORDENES (DETALLE) values ('Fish - Bones');
insert into ORDENES (DETALLE) values ('Nut - Almond, Blanched, Whole');
insert into ORDENES (DETALLE) values ('Blouse / Shirt / Sweater');
insert into ORDENES (DETALLE) values ('Beef - Bones, Cut - Up');
insert into ORDENES (DETALLE) values ('Island Oasis - Wildberry');
insert into ORDENES (DETALLE) values ('Vodka - Hot, Lnferno');
insert into ORDENES (DETALLE) values ('Muffin Mix - Carrot');
insert into ORDENES (DETALLE) values ('Pork - Loin, Bone - In');
insert into ORDENES (DETALLE) values ('Nectarines');
insert into ORDENES (DETALLE) values ('Sprite, Diet - 355ml');
insert into ORDENES (DETALLE) values ('Wine - Magnotta, Merlot Sr Vqa');
insert into ORDENES (DETALLE) values ('Soupcontfoam16oz 116con');
insert into ORDENES (DETALLE) values ('Snapple Raspberry Tea');
insert into ORDENES (DETALLE) values ('Oil - Margarine');
insert into ORDENES (DETALLE) values ('Wine - White, Pinot Grigio');
insert into ORDENES (DETALLE) values ('Garam Marsala');
insert into ORDENES (DETALLE) values ('Brandy Cherry - Mcguinness');
insert into ORDENES (DETALLE) values ('Lamb - Rack');
insert into ORDENES (DETALLE) values ('Gherkin - Sour');
insert into ORDENES (DETALLE) values ('Cheese - Provolone');
insert into ORDENES (DETALLE) values ('Kale - Red');
insert into ORDENES (DETALLE) values ('Cheese - Cheddar With Claret');
insert into ORDENES (DETALLE) values ('Sugar - Fine');
insert into ORDENES (DETALLE) values ('Beef - Eye Of Round');
insert into ORDENES (DETALLE) values ('Squash - Pattypan, Yellow');
insert into ORDENES (DETALLE) values ('Capers - Pickled');
insert into ORDENES (DETALLE) values ('Onions - Red');
insert into ORDENES (DETALLE) values ('Melon - Watermelon, Seedless');
insert into ORDENES (DETALLE) values ('Carrots - Purple, Organic');
insert into ORDENES (DETALLE) values ('Pastry - Butterscotch Baked');
insert into ORDENES (DETALLE) values ('Chervil - Fresh');
insert into ORDENES (DETALLE) values ('Mace Ground');
insert into ORDENES (DETALLE) values ('Napkin - Beverage 1 Ply');
insert into ORDENES (DETALLE) values ('Cake Circle, Foil, Scallop');
insert into ORDENES (DETALLE) values ('Garlic - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Juice - Ocean Spray Cranberry');
insert into ORDENES (DETALLE) values ('Wine - Duboeuf Beaujolais');
insert into ORDENES (DETALLE) values ('Wine - Soave Folonari');
insert into ORDENES (DETALLE) values ('Mustard - Dry, Powder');
insert into ORDENES (DETALLE) values ('Extract - Rum');
insert into ORDENES (DETALLE) values ('Veal - Striploin');
insert into ORDENES (DETALLE) values ('Lobster - Base');
insert into ORDENES (DETALLE) values ('Asparagus - White, Fresh');
insert into ORDENES (DETALLE) values ('Cheese - Cheddar, Medium');
insert into ORDENES (DETALLE) values ('Ice Cream Bar - Oreo Cone');
insert into ORDENES (DETALLE) values ('Veal - Nuckle');
insert into ORDENES (DETALLE) values ('Horseradish Root');
insert into ORDENES (DETALLE) values ('Pepper - Julienne, Frozen');
insert into ORDENES (DETALLE) values ('Wanton Wrap');
insert into ORDENES (DETALLE) values ('Tomatoes - Orange');
insert into ORDENES (DETALLE) values ('Soup - Knorr, Veg / Beef');
insert into ORDENES (DETALLE) values ('Cream Of Tartar');
insert into ORDENES (DETALLE) values ('Wine - Sake');
insert into ORDENES (DETALLE) values ('Wine - Magnotta, Merlot Sr Vqa');
insert into ORDENES (DETALLE) values ('Wine - Magnotta - Red, Baco');
insert into ORDENES (DETALLE) values ('Calypso - Strawberry Lemonade');
insert into ORDENES (DETALLE) values ('Cranberries - Frozen');
insert into ORDENES (DETALLE) values ('Bar Energy Chocchip');
insert into ORDENES (DETALLE) values ('Wine - Sicilia Igt Nero Avola');
insert into ORDENES (DETALLE) values ('Wine - Red, Wolf Blass, Yellow');
insert into ORDENES (DETALLE) values ('Lamb - Whole Head Off,nz');
insert into ORDENES (DETALLE) values ('Cheese - Brick With Pepper');
insert into ORDENES (DETALLE) values ('Lamb - Whole, Frozen');
insert into ORDENES (DETALLE) values ('Foam Cup 6 Oz');
insert into ORDENES (DETALLE) values ('Sambuca Cream');
insert into ORDENES (DETALLE) values ('Pastry - Apple Muffins - Mini');
insert into ORDENES (DETALLE) values ('Bread - Rosemary Focaccia');
insert into ORDENES (DETALLE) values ('Pepper - White, Whole');
insert into ORDENES (DETALLE) values ('Soup - Campbells Broccoli');
insert into ORDENES (DETALLE) values ('Salt And Pepper Mix - White');
insert into ORDENES (DETALLE) values ('Browning Caramel Glace');
insert into ORDENES (DETALLE) values ('Red Currant Jelly');
insert into ORDENES (DETALLE) values ('Ice Cream Bar - Hageen Daz To');
insert into ORDENES (DETALLE) values ('Flour - Bread');
insert into ORDENES (DETALLE) values ('Onions - Red');
insert into ORDENES (DETALLE) values ('Wine - Cave Springs Dry Riesling');
insert into ORDENES (DETALLE) values ('The Pop Shoppe - Lime Rickey');
insert into ORDENES (DETALLE) values ('Cloves - Whole');
insert into ORDENES (DETALLE) values ('Wine - Shiraz South Eastern');
insert into ORDENES (DETALLE) values ('Cheese - Comte');
insert into ORDENES (DETALLE) values ('Rum - White, Gg White');
insert into ORDENES (DETALLE) values ('Ecolab Digiclean Mild Fm');
insert into ORDENES (DETALLE) values ('Liquid Aminios Acid - Braggs');
insert into ORDENES (DETALLE) values ('Wine - Red, Pelee Island Merlot');
insert into ORDENES (DETALLE) values ('Soup - Campbells, Chix Gumbo');
insert into ORDENES (DETALLE) values ('Soup - Knorr, Veg / Beef');
insert into ORDENES (DETALLE) values ('Juice - Prune');
insert into ORDENES (DETALLE) values ('Bread - Sour Batard');
insert into ORDENES (DETALLE) values ('Beef - Eye Of Round');
insert into ORDENES (DETALLE) values ('Salt - Kosher');
insert into ORDENES (DETALLE) values ('Lamb Rack Frenched Australian');
insert into ORDENES (DETALLE) values ('Juice - Ocean Spray Cranberry');
insert into ORDENES (DETALLE) values ('Pork - Loin, Boneless');
insert into ORDENES (DETALLE) values ('Wine - Chateauneuf Du Pape');
insert into ORDENES (DETALLE) values ('Soup - Campbells - Tomato');
insert into ORDENES (DETALLE) values ('Muffin - Carrot Individual Wrap');
insert into ORDENES (DETALLE) values ('Chinese Foods - Chicken');
insert into ORDENES (DETALLE) values ('Pears - Anjou');
insert into ORDENES (DETALLE) values ('Capers - Ox Eye Daisy');
insert into ORDENES (DETALLE) values ('Carbonated Water - White Grape');
insert into ORDENES (DETALLE) values ('Cheese - Gorgonzola');
insert into ORDENES (DETALLE) values ('Shrimp - Baby, Warm Water');
insert into ORDENES (DETALLE) values ('Flour - Cake');
insert into ORDENES (DETALLE) values ('Dip - Tapenade');
insert into ORDENES (DETALLE) values ('Cheese - Brick With Onion');
insert into ORDENES (DETALLE) values ('Tomatoes Tear Drop Yellow');
insert into ORDENES (DETALLE) values ('Rum - Dark, Bacardi, Black');
insert into ORDENES (DETALLE) values ('Juice - V8 Splash');
insert into ORDENES (DETALLE) values ('Loquat');
insert into ORDENES (DETALLE) values ('Cheese - Brick With Pepper');
insert into ORDENES (DETALLE) values ('Appetizer - Seafood Assortment');
insert into ORDENES (DETALLE) values ('Kumquat');
insert into ORDENES (DETALLE) values ('Cheese - Brie, Cups 125g');
insert into ORDENES (DETALLE) values ('Ham - Cooked Bayonne Tinned');
insert into ORDENES (DETALLE) values ('Pickerel - Fillets');
insert into ORDENES (DETALLE) values ('Clams - Bay');
insert into ORDENES (DETALLE) values ('Sprouts Dikon');
insert into ORDENES (DETALLE) values ('Water - Green Tea Refresher');
insert into ORDENES (DETALLE) values ('Longos - Chicken Caeser Salad');
insert into ORDENES (DETALLE) values ('Bread - White Mini Epi');
insert into ORDENES (DETALLE) values ('Lamb - Loin Chops');
insert into ORDENES (DETALLE) values ('Pancetta');
insert into ORDENES (DETALLE) values ('Ham - Black Forest');
insert into ORDENES (DETALLE) values ('Muffin Batt - Ban Dream Zero');
insert into ORDENES (DETALLE) values ('Wine - Pinot Noir Mondavi Coastal');
insert into ORDENES (DETALLE) values ('Parsley - Dried');
insert into ORDENES (DETALLE) values ('Tendrils - Baby Pea, Organic');
insert into ORDENES (DETALLE) values ('Mushroom - Morels, Dry');
insert into ORDENES (DETALLE) values ('Kippers - Smoked');
insert into ORDENES (DETALLE) values ('Horseradish - Prepared');
insert into ORDENES (DETALLE) values ('Beef - Cow Feet Split');
insert into ORDENES (DETALLE) values ('Juice - Cranberry, 341 Ml');
insert into ORDENES (DETALLE) values ('Sausage - Andouille');
insert into ORDENES (DETALLE) values ('Shichimi Togarashi Peppeers');
insert into ORDENES (DETALLE) values ('Bread - Sticks, Thin, Plain');
insert into ORDENES (DETALLE) values ('Veal - Brisket, Provimi, Bone - In');
insert into ORDENES (DETALLE) values ('Pasta - Angel Hair');
insert into ORDENES (DETALLE) values ('Vinegar - Champagne');
insert into ORDENES (DETALLE) values ('Wine - Magnotta - Cab Sauv');
insert into ORDENES (DETALLE) values ('Crab - Claws, 26 - 30');
insert into ORDENES (DETALLE) values ('Guava');
insert into ORDENES (DETALLE) values ('Pork - Back Ribs');
insert into ORDENES (DETALLE) values ('Garlic');
insert into ORDENES (DETALLE) values ('Energy Drink - Franks Original');
insert into ORDENES (DETALLE) values ('Cheese - Blue');
insert into ORDENES (DETALLE) values ('Wild Boar - Tenderloin');
insert into ORDENES (DETALLE) values ('Lamb - Leg, Diced');
insert into ORDENES (DETALLE) values ('Pears - Bartlett');
insert into ORDENES (DETALLE) values ('Jolt Cola - Electric Blue');
insert into ORDENES (DETALLE) values ('Eggplant Italian');
insert into ORDENES (DETALLE) values ('Ice Cream Bar - Hagen Daz');
insert into ORDENES (DETALLE) values ('Figs');
insert into ORDENES (DETALLE) values ('Macaroons - Two Bite Choc');
insert into ORDENES (DETALLE) values ('Nacho Chips');
insert into ORDENES (DETALLE) values ('Coffee Cup 16oz Foam');
insert into ORDENES (DETALLE) values ('Appetizer - Veg Assortment');
insert into ORDENES (DETALLE) values ('Chicken - Diced, Cooked');
insert into ORDENES (DETALLE) values ('Cheese - Swiss Sliced');
insert into ORDENES (DETALLE) values ('Beef - Prime Rib Aaa');
insert into ORDENES (DETALLE) values ('Sparkling Wine - Rose, Freixenet');
insert into ORDENES (DETALLE) values ('Oranges');
insert into ORDENES (DETALLE) values ('Carbonated Water - Blackberry');
insert into ORDENES (DETALLE) values ('Yoghurt Tubes');
insert into ORDENES (DETALLE) values ('Ginger - Ground');
insert into ORDENES (DETALLE) values ('Pork - Ham Hocks - Smoked');
insert into ORDENES (DETALLE) values ('Venison - Ground');
insert into ORDENES (DETALLE) values ('Artichoke - Bottom, Canned');
insert into ORDENES (DETALLE) values ('Bread - Dark Rye, Loaf');
insert into ORDENES (DETALLE) values ('Cream - 18%');
insert into ORDENES (DETALLE) values ('Chambord Royal');
insert into ORDENES (DETALLE) values ('Cherries - Maraschino,jar');
insert into ORDENES (DETALLE) values ('Broom And Broom Rack White');
insert into ORDENES (DETALLE) values ('Cheese - Gouda');
insert into ORDENES (DETALLE) values ('Cocoa Powder - Natural');
insert into ORDENES (DETALLE) values ('Red Snapper - Fresh, Whole');
insert into ORDENES (DETALLE) values ('Soup - Campbells Chicken');
insert into ORDENES (DETALLE) values ('Nantucket - Orange Mango Cktl');
insert into ORDENES (DETALLE) values ('Bouillion - Fish');
insert into ORDENES (DETALLE) values ('Cumin - Ground');
insert into ORDENES (DETALLE) values ('Tea - Lemon Scented');
insert into ORDENES (DETALLE) values ('Tea - Darjeeling, Azzura');
insert into ORDENES (DETALLE) values ('Wine - Casillero Deldiablo');
insert into ORDENES (DETALLE) values ('Nantuket Peach Orange');
insert into ORDENES (DETALLE) values ('Cheese - Havarti, Roasted Garlic');
insert into ORDENES (DETALLE) values ('Bread - Roll, Canadian Dinner');
insert into ORDENES (DETALLE) values ('Energy Drink - Redbull 355ml');
insert into ORDENES (DETALLE) values ('Wine - Niagara,vqa Reisling');
insert into ORDENES (DETALLE) values ('Muffin Mix - Oatmeal');
insert into ORDENES (DETALLE) values ('Sauerkraut');
insert into ORDENES (DETALLE) values ('Soap - Pine Sol Floor Cleaner');
insert into ORDENES (DETALLE) values ('Venison - Striploin');
insert into ORDENES (DETALLE) values ('Pasta - Ravioli');
insert into ORDENES (DETALLE) values ('Chips Potato Salt Vinegar 43g');
insert into ORDENES (DETALLE) values ('Lid Coffeecup 12oz D9542b');
insert into ORDENES (DETALLE) values ('Soup - Cream Of Broccoli');
insert into ORDENES (DETALLE) values ('Beer - Blue');
insert into ORDENES (DETALLE) values ('Lemonade - Strawberry, 591 Ml');
insert into ORDENES (DETALLE) values ('Cheese Cloth No 100');
insert into ORDENES (DETALLE) values ('Pesto - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Chinese Lemon Pork');
insert into ORDENES (DETALLE) values ('Tea - Grapefruit Green Tea');
insert into ORDENES (DETALLE) values ('Cheese - La Sauvagine');
insert into ORDENES (DETALLE) values ('Butter - Salted, Micro');
insert into ORDENES (DETALLE) values ('Meldea Green Tea Liquor');
insert into ORDENES (DETALLE) values ('Figs');
insert into ORDENES (DETALLE) values ('Lotus Rootlets - Canned');
insert into ORDENES (DETALLE) values ('Eggplant - Baby');
insert into ORDENES (DETALLE) values ('Beef Cheek Fresh');
insert into ORDENES (DETALLE) values ('Madeira');
insert into ORDENES (DETALLE) values ('Table Cloth 54x72 Colour');
insert into ORDENES (DETALLE) values ('Dates');
insert into ORDENES (DETALLE) values ('Dc - Sakura Fu');
insert into ORDENES (DETALLE) values ('Pie Filling - Apple');
insert into ORDENES (DETALLE) values ('Allspice - Jamaican');
insert into ORDENES (DETALLE) values ('Cheese - Marble');
insert into ORDENES (DETALLE) values ('The Pop Shoppe - Grape');
insert into ORDENES (DETALLE) values ('Lettuce - Sea / Sea Asparagus');
insert into ORDENES (DETALLE) values ('Walkers Special Old Whiskey');
insert into ORDENES (DETALLE) values ('Food Colouring - Pink');
insert into ORDENES (DETALLE) values ('Tea - Lemon Green Tea');
insert into ORDENES (DETALLE) values ('Sauce - Plum');
insert into ORDENES (DETALLE) values ('Bonito Flakes - Toku Katsuo');
insert into ORDENES (DETALLE) values ('Sobe - Cranberry Grapefruit');
insert into ORDENES (DETALLE) values ('Soup - Campbells - Tomato');
insert into ORDENES (DETALLE) values ('Rice - Basmati');
insert into ORDENES (DETALLE) values ('Appetizer - Seafood Assortment');
insert into ORDENES (DETALLE) values ('Squash - Guords');
insert into ORDENES (DETALLE) values ('Appetizer - Asian Shrimp Roll');
insert into ORDENES (DETALLE) values ('Container - Clear 16 Oz');
insert into ORDENES (DETALLE) values ('Beer - Sleeman Fine Porter');
insert into ORDENES (DETALLE) values ('Yeast Dry - Fermipan');
insert into ORDENES (DETALLE) values ('Container - Clear 16 Oz');
insert into ORDENES (DETALLE) values ('Kolrabi');
insert into ORDENES (DETALLE) values ('Food Colouring - Green');
insert into ORDENES (DETALLE) values ('Five Alive Citrus');
insert into ORDENES (DETALLE) values ('Cheese - Camembert');
insert into ORDENES (DETALLE) values ('Soup - Cream Of Broccoli, Dry');
insert into ORDENES (DETALLE) values ('Marzipan 50/50');
insert into ORDENES (DETALLE) values ('Beans - Kidney, Red Dry');
insert into ORDENES (DETALLE) values ('Lobster - Baby, Boiled');
insert into ORDENES (DETALLE) values ('Pepper - Black, Crushed');
insert into ORDENES (DETALLE) values ('Cheese - Brie Roitelet');
insert into ORDENES (DETALLE) values ('Lid - 3oz Med Rec');
insert into ORDENES (DETALLE) values ('Milk - 1%');
insert into ORDENES (DETALLE) values ('Squash - Pattypan, Yellow');
insert into ORDENES (DETALLE) values ('Turkey - Breast, Boneless Sk On');
insert into ORDENES (DETALLE) values ('Mushroom - Chantrelle, Fresh');
insert into ORDENES (DETALLE) values ('Muffin Hinge - 211n');
insert into ORDENES (DETALLE) values ('Bread - Crusty Italian Poly');
insert into ORDENES (DETALLE) values ('Pasta - Penne, Lisce, Dry');
insert into ORDENES (DETALLE) values ('Lamb - Shoulder');
insert into ORDENES (DETALLE) values ('Asparagus - Mexican');
insert into ORDENES (DETALLE) values ('Bread - Mini Hamburger Bun');
insert into ORDENES (DETALLE) values ('Sambuca - Opal Nera');
insert into ORDENES (DETALLE) values ('Oxtail - Cut');
insert into ORDENES (DETALLE) values ('Cherries - Frozen');
insert into ORDENES (DETALLE) values ('Cookies Almond Hazelnut');
insert into ORDENES (DETALLE) values ('Bacardi Limon');
insert into ORDENES (DETALLE) values ('Cleaner - Comet');
insert into ORDENES (DETALLE) values ('Wine - Barbera Alba Doc 2001');
insert into ORDENES (DETALLE) values ('Compound - Rum');
insert into ORDENES (DETALLE) values ('Wine - Segura Viudas Aria Brut');
insert into ORDENES (DETALLE) values ('Mushroom - King Eryingii');
insert into ORDENES (DETALLE) values ('Bar Nature Valley');
insert into ORDENES (DETALLE) values ('Bar - Granola Trail Mix Fruit Nut');
insert into ORDENES (DETALLE) values ('Wine - Baron De Rothschild');
insert into ORDENES (DETALLE) values ('Glove - Cutting');
insert into ORDENES (DETALLE) values ('Propel Sport Drink');
insert into ORDENES (DETALLE) values ('Shiro Miso');
insert into ORDENES (DETALLE) values ('Curry Powder Madras');
insert into ORDENES (DETALLE) values ('Cookies - Fortune');
insert into ORDENES (DETALLE) values ('Nut - Walnut, Pieces');
insert into ORDENES (DETALLE) values ('Pork - Caul Fat');
insert into ORDENES (DETALLE) values ('Salt And Pepper Mix - Black');
insert into ORDENES (DETALLE) values ('Wiberg Super Cure');
insert into ORDENES (DETALLE) values ('Chicken - Leg / Back Attach');
insert into ORDENES (DETALLE) values ('Blackberries');
insert into ORDENES (DETALLE) values ('Vinegar - Rice');
insert into ORDENES (DETALLE) values ('Chicken - Whole Fryers');
insert into ORDENES (DETALLE) values ('Bread Base - Gold Formel');
insert into ORDENES (DETALLE) values ('Wasabi Paste');
insert into ORDENES (DETALLE) values ('Onions - White');
insert into ORDENES (DETALLE) values ('Chocolate - Milk');
insert into ORDENES (DETALLE) values ('Pur Value');
insert into ORDENES (DETALLE) values ('Coke - Classic, 355 Ml');
insert into ORDENES (DETALLE) values ('Pork - Suckling Pig');
insert into ORDENES (DETALLE) values ('Almonds Ground Blanched');
insert into ORDENES (DETALLE) values ('Kumquat');
insert into ORDENES (DETALLE) values ('Wine - Magnotta - Bel Paese White');
insert into ORDENES (DETALLE) values ('Wine - Red, Gallo, Merlot');
insert into ORDENES (DETALLE) values ('Wanton Wrap');
insert into ORDENES (DETALLE) values ('Carrots - Mini Red Organic');
insert into ORDENES (DETALLE) values ('Crab - Meat Combo');
insert into ORDENES (DETALLE) values ('Table Cloth 81x81 Colour');
insert into ORDENES (DETALLE) values ('Pasta - Penne Primavera, Single');
insert into ORDENES (DETALLE) values ('Octopus');
insert into ORDENES (DETALLE) values ('Onions - Green');
insert into ORDENES (DETALLE) values ('Pepper - Red, Finger Hot');
insert into ORDENES (DETALLE) values ('Tofu - Soft');
insert into ORDENES (DETALLE) values ('Table Cloth 81x81 White');
insert into ORDENES (DETALLE) values ('Muffin Mix - Raisin Bran');
insert into ORDENES (DETALLE) values ('Appetizer - Cheese Bites');
insert into ORDENES (DETALLE) values ('Cheese - Brie');
insert into ORDENES (DETALLE) values ('Clam Nectar');
insert into ORDENES (DETALLE) values ('Pineapple - Canned, Rings');
insert into ORDENES (DETALLE) values ('Bananas');
insert into ORDENES (DETALLE) values ('Yogurt - Banana, 175 Gr');
insert into ORDENES (DETALLE) values ('Oil - Olive');
insert into ORDENES (DETALLE) values ('Beef - Tongue, Fresh');
insert into ORDENES (DETALLE) values ('Rice Paper');
insert into ORDENES (DETALLE) values ('Snapple - Iced Tea Peach');
insert into ORDENES (DETALLE) values ('Wine - Vidal Icewine Magnotta');
insert into ORDENES (DETALLE) values ('Salt And Pepper Mix - White');
insert into ORDENES (DETALLE) values ('Boogies');
insert into ORDENES (DETALLE) values ('Cup - 6oz, Foam');
insert into ORDENES (DETALLE) values ('Nut - Peanut, Roasted');
insert into ORDENES (DETALLE) values ('Bread - White, Sliced');
insert into ORDENES (DETALLE) values ('Molasses - Fancy');
insert into ORDENES (DETALLE) values ('Bread Base - Toscano');
insert into ORDENES (DETALLE) values ('Pepper - Roasted Red');
insert into ORDENES (DETALLE) values ('Veal Inside - Provimi');
insert into ORDENES (DETALLE) values ('Sprouts - Onion');
insert into ORDENES (DETALLE) values ('Capicola - Hot');
insert into ORDENES (DETALLE) values ('Flour - All Purpose');
insert into ORDENES (DETALLE) values ('Ecolab Digiclean Mild Fm');
insert into ORDENES (DETALLE) values ('Tomato - Peeled Italian Canned');
insert into ORDENES (DETALLE) values ('Veal - Osso Bucco');
insert into ORDENES (DETALLE) values ('Wine - White, Riesling, Semi - Dry');
insert into ORDENES (DETALLE) values ('Jam - Raspberry');
insert into ORDENES (DETALLE) values ('Oneshot Automatic Soap System');
insert into ORDENES (DETALLE) values ('Pumpkin');
insert into ORDENES (DETALLE) values ('Bagel - 12 Grain Preslice');
insert into ORDENES (DETALLE) values ('Chicken - Wieners');
insert into ORDENES (DETALLE) values ('Sobe - Berry Energy');
insert into ORDENES (DETALLE) values ('Towels - Paper / Kraft');
insert into ORDENES (DETALLE) values ('Rum - White, Gg White');
insert into ORDENES (DETALLE) values ('Veal - Striploin');
insert into ORDENES (DETALLE) values ('Dried Apple');
insert into ORDENES (DETALLE) values ('Nut - Almond, Blanched, Sliced');
insert into ORDENES (DETALLE) values ('Wine - Chablis J Moreau Et Fils');
insert into ORDENES (DETALLE) values ('Cake - Box Window 10x10x2.5');
insert into ORDENES (DETALLE) values ('Pepper - Green, Chili');
insert into ORDENES (DETALLE) values ('Artichoke - Hearts, Canned');
insert into ORDENES (DETALLE) values ('Chocolate Eclairs');
insert into ORDENES (DETALLE) values ('Trueblue - Blueberry');
insert into ORDENES (DETALLE) values ('V8 - Vegetable Cocktail');
insert into ORDENES (DETALLE) values ('Glove - Cutting');
insert into ORDENES (DETALLE) values ('Pastry - Lemon Danish - Mini');
insert into ORDENES (DETALLE) values ('Pepper - White, Ground');
insert into ORDENES (DETALLE) values ('Thyme - Fresh');
insert into ORDENES (DETALLE) values ('Juice - Lime');
insert into ORDENES (DETALLE) values ('Beans - Fava Fresh');
insert into ORDENES (DETALLE) values ('Lid - Translucent, 3.5 And 6 Oz');
insert into ORDENES (DETALLE) values ('Chilli Paste, Sambal Oelek');
insert into ORDENES (DETALLE) values ('Beer - Molson Excel');
insert into ORDENES (DETALLE) values ('Ecolab - Lime - A - Way 4/4 L');
insert into ORDENES (DETALLE) values ('Assorted Desserts');
insert into ORDENES (DETALLE) values ('Wine - White, Ej');
insert into ORDENES (DETALLE) values ('Kaffir Lime Leaves');
insert into ORDENES (DETALLE) values ('Appetizer - Crab And Brie');
insert into ORDENES (DETALLE) values ('Foil - 4oz Custard Cup');
insert into ORDENES (DETALLE) values ('Pail - 15l White, With Handle');
insert into ORDENES (DETALLE) values ('Eggplant - Baby');
insert into ORDENES (DETALLE) values ('Water - Perrier');
insert into ORDENES (DETALLE) values ('Bay Leaf Ground');
insert into ORDENES (DETALLE) values ('Ostrich - Prime Cut');
insert into ORDENES (DETALLE) values ('Wanton Wrap');
insert into ORDENES (DETALLE) values ('Ostrich - Fan Fillet');
insert into ORDENES (DETALLE) values ('Wine - Two Oceans Sauvignon');
insert into ORDENES (DETALLE) values ('Bacardi Mojito');
insert into ORDENES (DETALLE) values ('Milk - Buttermilk');
insert into ORDENES (DETALLE) values ('Muffin - Mix - Strawberry Rhubarb');
insert into ORDENES (DETALLE) values ('Water Chestnut - Canned');
insert into ORDENES (DETALLE) values ('Ice Cream - Strawberry');
insert into ORDENES (DETALLE) values ('Bread Ww Cluster');
insert into ORDENES (DETALLE) values ('Wiberg Super Cure');
insert into ORDENES (DETALLE) values ('Jolt Cola');
insert into ORDENES (DETALLE) values ('Sansho Powder');
insert into ORDENES (DETALLE) values ('Bagel - Sesame Seed Presliced');
insert into ORDENES (DETALLE) values ('Sugar Thermometer');
insert into ORDENES (DETALLE) values ('Pears - Bartlett');
insert into ORDENES (DETALLE) values ('Bagel - Everything Presliced');
insert into ORDENES (DETALLE) values ('Tortillas - Flour, 8');
insert into ORDENES (DETALLE) values ('Bread - Hamburger Buns');
insert into ORDENES (DETALLE) values ('Sugar Thermometer');
insert into ORDENES (DETALLE) values ('Cheese - Ermite Bleu');
insert into ORDENES (DETALLE) values ('Arctic Char - Fillets');
insert into ORDENES (DETALLE) values ('Lemonade - Black Cherry, 591 Ml');
insert into ORDENES (DETALLE) values ('Asparagus - White, Fresh');
insert into ORDENES (DETALLE) values ('Gelatine Powder');
insert into ORDENES (DETALLE) values ('Flower - Carnations');
insert into ORDENES (DETALLE) values ('Kellogs Raisan Bran Bars');
insert into ORDENES (DETALLE) values ('Wine - Casillero Del Diablo');
insert into ORDENES (DETALLE) values ('Cheese - Havarti, Salsa');
insert into ORDENES (DETALLE) values ('Cabbage Roll');
insert into ORDENES (DETALLE) values ('Lettuce - Spring Mix');
insert into ORDENES (DETALLE) values ('Pastry - Lemon Danish - Mini');
insert into ORDENES (DETALLE) values ('Chocolate - Unsweetened');
insert into ORDENES (DETALLE) values ('Crab - Meat Combo');
insert into ORDENES (DETALLE) values ('Muffin Batt - Ban Dream Zero');
insert into ORDENES (DETALLE) values ('Burger Veggie');
insert into ORDENES (DETALLE) values ('Apple - Delicious, Red');
insert into ORDENES (DETALLE) values ('Pasta - Linguini, Dry');
insert into ORDENES (DETALLE) values ('Oil - Sunflower');
insert into ORDENES (DETALLE) values ('Pork Ham Prager');
insert into ORDENES (DETALLE) values ('Clams - Canned');
insert into ORDENES (DETALLE) values ('Tea - Darjeeling, Azzura');
insert into ORDENES (DETALLE) values ('Lamb - Shanks');
insert into ORDENES (DETALLE) values ('Cakes Assorted');
insert into ORDENES (DETALLE) values ('Juice - V8, Tomato');
insert into ORDENES (DETALLE) values ('Chicken - Soup Base');
insert into ORDENES (DETALLE) values ('Veal - Insides, Grains');
insert into ORDENES (DETALLE) values ('Sauce - Marinara');
insert into ORDENES (DETALLE) values ('Cornstarch');
insert into ORDENES (DETALLE) values ('Soup - Beef Conomme, Dry');
insert into ORDENES (DETALLE) values ('Brocolinni - Gaylan, Chinese');
insert into ORDENES (DETALLE) values ('Sauce - Rosee');
insert into ORDENES (DETALLE) values ('Butter - Salted');
insert into ORDENES (DETALLE) values ('Madeira');
insert into ORDENES (DETALLE) values ('Soup - French Onion');
insert into ORDENES (DETALLE) values ('Beef - Ox Tail, Frozen');
insert into ORDENES (DETALLE) values ('Appetizer - Southwestern');
insert into ORDENES (DETALLE) values ('Muffin Hinge 117n');
insert into ORDENES (DETALLE) values ('Beer - Pilsner Urquell');
insert into ORDENES (DETALLE) values ('Melon - Cantaloupe');
insert into ORDENES (DETALLE) values ('Stock - Chicken, White');
insert into ORDENES (DETALLE) values ('Olives - Stuffed');
insert into ORDENES (DETALLE) values ('Veal - Shank, Pieces');
insert into ORDENES (DETALLE) values ('Ocean Spray - Ruby Red');
insert into ORDENES (DETALLE) values ('Extract - Lemon');
insert into ORDENES (DETALLE) values ('Coffee - Hazelnut Cream');
insert into ORDENES (DETALLE) values ('Spinach - Frozen');
insert into ORDENES (DETALLE) values ('Puree - Blackcurrant');
insert into ORDENES (DETALLE) values ('Roe - White Fish');
insert into ORDENES (DETALLE) values ('Oil - Grapeseed Oil');
insert into ORDENES (DETALLE) values ('Beef Dry Aged Tenderloin Aaa');
insert into ORDENES (DETALLE) values ('Juice - Mango');
insert into ORDENES (DETALLE) values ('Aspic - Clear');
insert into ORDENES (DETALLE) values ('Lentils - Red, Dry');
insert into ORDENES (DETALLE) values ('Trout - Rainbow, Frozen');
insert into ORDENES (DETALLE) values ('Salt - Kosher');
insert into ORDENES (DETALLE) values ('Yucca');
insert into ORDENES (DETALLE) values ('Wine - White Cab Sauv.on');
insert into ORDENES (DETALLE) values ('Cookies Almond Hazelnut');
insert into ORDENES (DETALLE) values ('Cheese - Ricotta');
insert into ORDENES (DETALLE) values ('Beer - Camerons Auburn');
insert into ORDENES (DETALLE) values ('Flax Seed');
insert into ORDENES (DETALLE) values ('Beef Flat Iron Steak');
insert into ORDENES (DETALLE) values ('Cheese - Mascarpone');
insert into ORDENES (DETALLE) values ('Lettuce - Sea / Sea Asparagus');
insert into ORDENES (DETALLE) values ('Beans - Turtle, Black, Dry');
insert into ORDENES (DETALLE) values ('Magnotta - Bel Paese White');
insert into ORDENES (DETALLE) values ('Gingerale - Schweppes, 355 Ml');
insert into ORDENES (DETALLE) values ('Ham - Cooked Bayonne Tinned');
insert into ORDENES (DETALLE) values ('Ginger - Ground');
insert into ORDENES (DETALLE) values ('Mix - Cocktail Ice Cream');
insert into ORDENES (DETALLE) values ('Oil - Coconut');
insert into ORDENES (DETALLE) values ('Papayas');
insert into ORDENES (DETALLE) values ('Sole - Fillet');
insert into ORDENES (DETALLE) values ('Lamb Shoulder Boneless Nz');
insert into ORDENES (DETALLE) values ('Wheat - Soft Kernal Of Wheat');
insert into ORDENES (DETALLE) values ('Pastry - Baked Cinnamon Stick');
insert into ORDENES (DETALLE) values ('Bacardi Raspberry');
insert into ORDENES (DETALLE) values ('Noodles - Steamed Chow Mein');
insert into ORDENES (DETALLE) values ('Pepper - Black, Crushed');
insert into ORDENES (DETALLE) values ('Beans - Black Bean, Preserved');
insert into ORDENES (DETALLE) values ('Lamb - Sausage Casings');
insert into ORDENES (DETALLE) values ('Veal - Heart');
insert into ORDENES (DETALLE) values ('Island Oasis - Mango Daiquiri');
insert into ORDENES (DETALLE) values ('Tomatoes Tear Drop');
insert into ORDENES (DETALLE) values ('Ostrich - Fan Fillet');
insert into ORDENES (DETALLE) values ('Hummus - Spread');
insert into ORDENES (DETALLE) values ('Wine - Red, Harrow Estates, Cab');
insert into ORDENES (DETALLE) values ('Squash - Guords');
insert into ORDENES (DETALLE) values ('Soap - Hand Soap');
insert into ORDENES (DETALLE) values ('Coffee - Cafe Moreno');
insert into ORDENES (DETALLE) values ('Longos - Greek Salad');
insert into ORDENES (DETALLE) values ('Pepperoni Slices');
insert into ORDENES (DETALLE) values ('Pastry - Baked Scones - Mini');
insert into ORDENES (DETALLE) values ('Bread - Petit Baguette');
insert into ORDENES (DETALLE) values ('Chocolate - Compound Coating');
insert into ORDENES (DETALLE) values ('Sugar - Brown');
insert into ORDENES (DETALLE) values ('Five Alive Citrus');
insert into ORDENES (DETALLE) values ('Fish - Base, Bouillion');
insert into ORDENES (DETALLE) values ('Ezy Change Mophandle');
insert into ORDENES (DETALLE) values ('Marzipan 50/50');
insert into ORDENES (DETALLE) values ('Muffin Batt - Blueberry Passion');
insert into ORDENES (DETALLE) values ('Lettuce - Red Leaf');
insert into ORDENES (DETALLE) values ('V8 Pet');
insert into ORDENES (DETALLE) values ('Sea Bass - Fillets');
insert into ORDENES (DETALLE) values ('Pork - Ham Hocks - Smoked');
insert into ORDENES (DETALLE) values ('Mustard Prepared');
insert into ORDENES (DETALLE) values ('Lettuce - Red Leaf');
insert into ORDENES (DETALLE) values ('Cookie Dough - Oatmeal Rasin');
insert into ORDENES (DETALLE) values ('Mushroom - King Eryingii');
insert into ORDENES (DETALLE) values ('Caviar - Salmon');
insert into ORDENES (DETALLE) values ('Cookies Oatmeal Raisin');
insert into ORDENES (DETALLE) values ('Yogurt - Assorted Pack');
insert into ORDENES (DETALLE) values ('Lamb - Loin Chops');
insert into ORDENES (DETALLE) values ('Shrimp - 31/40');
insert into ORDENES (DETALLE) values ('Garbage Bags - Clear');
insert into ORDENES (DETALLE) values ('Wine - Magnotta - Cab Sauv');
insert into ORDENES (DETALLE) values ('Sauce - Hollandaise');
insert into ORDENES (DETALLE) values ('Cheese - Mozzarella, Buffalo');
insert into ORDENES (DETALLE) values ('Cocoa Powder - Natural');
insert into ORDENES (DETALLE) values ('Cake - Cheese Cake 9 Inch');
insert into ORDENES (DETALLE) values ('Lentils - Green, Dry');
insert into ORDENES (DETALLE) values ('Muffin Mix - Carrot');
insert into ORDENES (DETALLE) values ('Muffin - Mix - Strawberry Rhubarb');
insert into ORDENES (DETALLE) values ('Pheasants - Whole');
insert into ORDENES (DETALLE) values ('Sauce - Roasted Red Pepper');
insert into ORDENES (DETALLE) values ('Turkey Leg With Drum And Thigh');
insert into ORDENES (DETALLE) values ('Schnappes Peppermint - Walker');
insert into ORDENES (DETALLE) values ('Glass - Juice Clear 5oz 55005');
insert into ORDENES (DETALLE) values ('Tomatillo');
insert into ORDENES (DETALLE) values ('Wine - White, Cooking');
insert into ORDENES (DETALLE) values ('Milk - Buttermilk');
insert into ORDENES (DETALLE) values ('Liqueur Banana, Ramazzotti');
insert into ORDENES (DETALLE) values ('Jolt Cola - Electric Blue');
insert into ORDENES (DETALLE) values ('Bread - Sour Batard');
insert into ORDENES (DETALLE) values ('Cheese - St. Paulin');
insert into ORDENES (DETALLE) values ('Pecan Raisin - Tarts');
insert into ORDENES (DETALLE) values ('Beef - Tenderloin - Aa');
insert into ORDENES (DETALLE) values ('Limes');
insert into ORDENES (DETALLE) values ('Squid Ink');
insert into ORDENES (DETALLE) values ('Pail With Metal Handle 16l White');
insert into ORDENES (DETALLE) values ('Chips Potato Reg 43g');
insert into ORDENES (DETALLE) values ('Wine - Cotes Du Rhone Parallele');
insert into ORDENES (DETALLE) values ('Whmis Spray Bottle Graduated');
insert into ORDENES (DETALLE) values ('Lid Tray - 16in Dome');
insert into ORDENES (DETALLE) values ('Swordfish Loin Portions');
insert into ORDENES (DETALLE) values ('Octopus');
insert into ORDENES (DETALLE) values ('Yogurt - Raspberry, 175 Gr');
insert into ORDENES (DETALLE) values ('Taro Root');
insert into ORDENES (DETALLE) values ('Squid - U - 10 Thailand');
insert into ORDENES (DETALLE) values ('Nut - Hazelnut, Whole');
insert into ORDENES (DETALLE) values ('Amaretto');
insert into ORDENES (DETALLE) values ('Marsala - Sperone, Fine, D.o.c.');
insert into ORDENES (DETALLE) values ('Jam - Raspberry');
insert into ORDENES (DETALLE) values ('Bok Choy - Baby');
insert into ORDENES (DETALLE) values ('Cake - Miini Cheesecake Cherry');
insert into ORDENES (DETALLE) values ('Salmon - Canned');
insert into ORDENES (DETALLE) values ('Tomatoes Tear Drop');
insert into ORDENES (DETALLE) values ('Kellogs Special K Cereal');
insert into ORDENES (DETALLE) values ('Crab - Claws, 26 - 30');
insert into ORDENES (DETALLE) values ('Ecolab - Solid Fusion');
insert into ORDENES (DETALLE) values ('Chicken - Whole Roasting');
insert into ORDENES (DETALLE) values ('Sauce - Thousand Island');
insert into ORDENES (DETALLE) values ('Pepper - Paprika, Hungarian');
insert into ORDENES (DETALLE) values ('Vanilla Beans');
insert into ORDENES (DETALLE) values ('Appetizer - Seafood Assortment');
insert into ORDENES (DETALLE) values ('Container - Hngd Cll Blk 7x7x3');
insert into ORDENES (DETALLE) values ('Broom - Angled');
insert into ORDENES (DETALLE) values ('Mints - Striped Red');
insert into ORDENES (DETALLE) values ('Appetizer - Lobster Phyllo Roll');
insert into ORDENES (DETALLE) values ('Ocean Spray - Kiwi Strawberry');
insert into ORDENES (DETALLE) values ('Pasta - Canelloni, Single Serve');
insert into ORDENES (DETALLE) values ('Bread - Pumpernickel');
insert into ORDENES (DETALLE) values ('Mushroom - Enoki, Fresh');
insert into ORDENES (DETALLE) values ('Olives - Morracan Dired');
insert into ORDENES (DETALLE) values ('Daves Island Stinger');
insert into ORDENES (DETALLE) values ('Mushrooms - Black, Dried');
insert into ORDENES (DETALLE) values ('Wine - Sogrape Mateus Rose');
insert into ORDENES (DETALLE) values ('Oven Mitts - 15 Inch');
insert into ORDENES (DETALLE) values ('Salt - Table');
insert into ORDENES (DETALLE) values ('Eggplant - Regular');
insert into ORDENES (DETALLE) values ('Spice - Paprika');
insert into ORDENES (DETALLE) values ('Potatoes - Instant, Mashed');
insert into ORDENES (DETALLE) values ('Pork - Tenderloin, Fresh');
insert into ORDENES (DETALLE) values ('Bread - Roll, Italian');
insert into ORDENES (DETALLE) values ('Flower - Daisies');
insert into ORDENES (DETALLE) values ('Wine - Pinot Noir Latour');
insert into ORDENES (DETALLE) values ('Snapple - Mango Maddness');
insert into ORDENES (DETALLE) values ('Kumquat');
insert into ORDENES (DETALLE) values ('Pastry - Cherry Danish - Mini');
insert into ORDENES (DETALLE) values ('Nut - Pecan, Pieces');
insert into ORDENES (DETALLE) values ('Flour - Cake');
insert into ORDENES (DETALLE) values ('Bread - English Muffin');
insert into ORDENES (DETALLE) values ('Seedlings - Clamshell');
insert into ORDENES (DETALLE) values ('Jolt Cola');
insert into ORDENES (DETALLE) values ('Chocolate Bar - Oh Henry');
insert into ORDENES (DETALLE) values ('Quinoa');
insert into ORDENES (DETALLE) values ('Lobster - Live');
insert into ORDENES (DETALLE) values ('Instant Coffee');
insert into ORDENES (DETALLE) values ('Herb Du Provence - Primerba');
insert into ORDENES (DETALLE) values ('Peppercorns - Green');
insert into ORDENES (DETALLE) values ('Wine - Coteaux Du Tricastin Ac');
insert into ORDENES (DETALLE) values ('Wonton Wrappers');
insert into ORDENES (DETALLE) values ('Cheese - Woolwich Goat, Log');
insert into ORDENES (DETALLE) values ('Crab - Meat');
insert into ORDENES (DETALLE) values ('Beef - Texas Style Burger');
insert into ORDENES (DETALLE) values ('Bagel - Sesame Seed Presliced');
insert into ORDENES (DETALLE) values ('Sauce - Soya, Light');
insert into ORDENES (DETALLE) values ('Towels - Paper / Kraft');
insert into ORDENES (DETALLE) values ('Ice Cream Bar - Oreo Sandwich');
insert into ORDENES (DETALLE) values ('Oil - Shortening,liqud, Fry');
insert into ORDENES (DETALLE) values ('Sugar - Sweet N Low, Individual');
insert into ORDENES (DETALLE) values ('Sauce - Oyster');
insert into ORDENES (DETALLE) values ('Pickle - Dill');
insert into ORDENES (DETALLE) values ('Tea - Honey Green Tea');
insert into ORDENES (DETALLE) values ('Soup - Beef, Base Mix');
insert into ORDENES (DETALLE) values ('Table Cloth 53x69 White');
insert into ORDENES (DETALLE) values ('Pork - Ham Hocks - Smoked');
insert into ORDENES (DETALLE) values ('Venison - Denver Leg Boneless');
insert into ORDENES (DETALLE) values ('Catfish - Fillets');
insert into ORDENES (DETALLE) values ('Mackerel Whole Fresh');
insert into ORDENES (DETALLE) values ('Cranberries - Frozen');
insert into ORDENES (DETALLE) values ('Tart Shells - Savory, 4');
insert into ORDENES (DETALLE) values ('Wine - Remy Pannier Rose');
insert into ORDENES (DETALLE) values ('Silicone Paper 16.5x24');
insert into ORDENES (DETALLE) values ('Marzipan 50/50');
insert into ORDENES (DETALLE) values ('Hagen Daza - Dk Choocolate');
insert into ORDENES (DETALLE) values ('Tomatoes - Roma');
insert into ORDENES (DETALLE) values ('Wine - Periguita Fonseca');
insert into ORDENES (DETALLE) values ('Hickory Smoke, Liquid');
insert into ORDENES (DETALLE) values ('Snapple Raspberry Tea');
insert into ORDENES (DETALLE) values ('Pasta - Angel Hair');
insert into ORDENES (DETALLE) values ('Lime Cordial - Roses');
insert into ORDENES (DETALLE) values ('Cleaner - Pine Sol');
insert into ORDENES (DETALLE) values ('Chickhen - Chicken Phyllo');
insert into ORDENES (DETALLE) values ('Basil - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Pastry - Lemon Danish - Mini');
insert into ORDENES (DETALLE) values ('Carbonated Water - White Grape');
insert into ORDENES (DETALLE) values ('Parsley - Fresh');
insert into ORDENES (DETALLE) values ('Lobster - Live');
insert into ORDENES (DETALLE) values ('Sorrel - Fresh');
insert into ORDENES (DETALLE) values ('Shiratamako - Rice Flour');
insert into ORDENES (DETALLE) values ('Longos - Lasagna Veg');
insert into ORDENES (DETALLE) values ('Crab - Claws, Snow 16 - 24');
insert into ORDENES (DETALLE) values ('Lid - Translucent, 3.5 And 6 Oz');
insert into ORDENES (DETALLE) values ('Wine - Red, Mouton Cadet');
insert into ORDENES (DETALLE) values ('Raspberries - Fresh');
insert into ORDENES (DETALLE) values ('Stock - Beef, Brown');
insert into ORDENES (DETALLE) values ('Ham - Smoked, Bone - In');
insert into ORDENES (DETALLE) values ('Wine - Magnotta, Merlot Sr Vqa');
insert into ORDENES (DETALLE) values ('Beef - Bones, Cut - Up');
insert into ORDENES (DETALLE) values ('Quail Eggs - Canned');
insert into ORDENES (DETALLE) values ('Oil - Shortening,liqud, Fry');
insert into ORDENES (DETALLE) values ('Tomatoes - Roma');
insert into ORDENES (DETALLE) values ('Dried Cherries');
insert into ORDENES (DETALLE) values ('Water - Spring Water, 355 Ml');
insert into ORDENES (DETALLE) values ('Nori Sea Weed');
insert into ORDENES (DETALLE) values ('Smoked Tongue');
insert into ORDENES (DETALLE) values ('Mousse - Banana Chocolate');
insert into ORDENES (DETALLE) values ('Everfresh Products');
insert into ORDENES (DETALLE) values ('Beer - Creemore');
insert into ORDENES (DETALLE) values ('Beef - Tongue, Cooked');
insert into ORDENES (DETALLE) values ('Rosemary - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Beef - Tenderloin');
insert into ORDENES (DETALLE) values ('Cookies Oatmeal Raisin');
insert into ORDENES (DETALLE) values ('Steampan - Half Size Shallow');
insert into ORDENES (DETALLE) values ('Sugar - Icing');
insert into ORDENES (DETALLE) values ('Table Cloth 53x69 White');
insert into ORDENES (DETALLE) values ('Onions - Green');
insert into ORDENES (DETALLE) values ('Hand Towel');
insert into ORDENES (DETALLE) values ('Bamboo Shoots - Sliced');
insert into ORDENES (DETALLE) values ('Cheese - Swiss Sliced');
insert into ORDENES (DETALLE) values ('Quail - Whole, Boneless');
insert into ORDENES (DETALLE) values ('Danishes - Mini Raspberry');
insert into ORDENES (DETALLE) values ('Raisin - Golden');
insert into ORDENES (DETALLE) values ('Ice - Clear, 300 Lb For Carving');
insert into ORDENES (DETALLE) values ('Bread - Mini Hamburger Bun');
insert into ORDENES (DETALLE) values ('Sauce - Black Current, Dry Mix');
insert into ORDENES (DETALLE) values ('Tia Maria');
insert into ORDENES (DETALLE) values ('Iced Tea - Lemon, 460 Ml');
insert into ORDENES (DETALLE) values ('Apricots Fresh');
insert into ORDENES (DETALLE) values ('Tequila - Sauza Silver');
insert into ORDENES (DETALLE) values ('Pasta - Cappellini, Dry');
insert into ORDENES (DETALLE) values ('Sauce - Black Current, Dry Mix');
insert into ORDENES (DETALLE) values ('Beef Dry Aged Tenderloin Aaa');
insert into ORDENES (DETALLE) values ('Jam - Blackberry, 20 Ml Jar');
insert into ORDENES (DETALLE) values ('Bread - Triangle White');
insert into ORDENES (DETALLE) values ('Banana Turning');
insert into ORDENES (DETALLE) values ('Glaze - Apricot');
insert into ORDENES (DETALLE) values ('Soup - Base Broth Chix');
insert into ORDENES (DETALLE) values ('Sugar - Brown, Individual');
insert into ORDENES (DETALLE) values ('Chocolate - Dark');
insert into ORDENES (DETALLE) values ('Bread - White Mini Epi');
insert into ORDENES (DETALLE) values ('Egg Patty Fried');
insert into ORDENES (DETALLE) values ('Sausage - Andouille');
insert into ORDENES (DETALLE) values ('Pate - Liver');
insert into ORDENES (DETALLE) values ('Otomegusa Dashi Konbu');
insert into ORDENES (DETALLE) values ('Bacardi Breezer - Tropical');
insert into ORDENES (DETALLE) values ('V8 Pet');
insert into ORDENES (DETALLE) values ('Bread Base - Gold Formel');
insert into ORDENES (DETALLE) values ('Water, Tap');
insert into ORDENES (DETALLE) values ('Red Currants');
insert into ORDENES (DETALLE) values ('Mushroom - Chanterelle Frozen');
insert into ORDENES (DETALLE) values ('Steampan Lid');
insert into ORDENES (DETALLE) values ('Glass - Juice Clear 5oz 55005');
insert into ORDENES (DETALLE) values ('Strawberries');
insert into ORDENES (DETALLE) values ('Bread Foccacia Whole');
insert into ORDENES (DETALLE) values ('Island Oasis - Peach Daiquiri');
insert into ORDENES (DETALLE) values ('Pasta - Fettuccine, Egg, Fresh');
insert into ORDENES (DETALLE) values ('Danishes - Mini Raspberry');
insert into ORDENES (DETALLE) values ('Chocolate - Milk, Callets');
insert into ORDENES (DETALLE) values ('Soup V8 Roasted Red Pepper');
insert into ORDENES (DETALLE) values ('Squid Ink');
insert into ORDENES (DETALLE) values ('Stock - Veal, White');
insert into ORDENES (DETALLE) values ('Icecream - Dstk Super Cone');
insert into ORDENES (DETALLE) values ('Lamb - Leg, Bone In');
insert into ORDENES (DETALLE) values ('Relish');
insert into ORDENES (DETALLE) values ('Beef - Prime Rib Aaa');
insert into ORDENES (DETALLE) values ('Garlic - Elephant');
insert into ORDENES (DETALLE) values ('Cake - Box Window 10x10x2.5');
insert into ORDENES (DETALLE) values ('Cheese - Swiss');
insert into ORDENES (DETALLE) values ('Pork - Bacon, Double Smoked');
insert into ORDENES (DETALLE) values ('Chips - Doritos');
insert into ORDENES (DETALLE) values ('Bread - Corn Muffaleta Onion');
insert into ORDENES (DETALLE) values ('Dill Weed - Dry');
insert into ORDENES (DETALLE) values ('Flower - Commercial Spider');
insert into ORDENES (DETALLE) values ('Cup Translucent 9 Oz');
insert into ORDENES (DETALLE) values ('Scallops - U - 10');
insert into ORDENES (DETALLE) values ('Corn Shoots');
insert into ORDENES (DETALLE) values ('Coke - Diet, 355 Ml');
insert into ORDENES (DETALLE) values ('Cake - Dulce De Leche');
insert into ORDENES (DETALLE) values ('Shiratamako - Rice Flour');
insert into ORDENES (DETALLE) values ('Skirt - 29 Foot');
insert into ORDENES (DETALLE) values ('Pernod');
insert into ORDENES (DETALLE) values ('Almonds Ground Blanched');
insert into ORDENES (DETALLE) values ('Vanilla Beans');
insert into ORDENES (DETALLE) values ('Bulgar');
insert into ORDENES (DETALLE) values ('Star Fruit');
insert into ORDENES (DETALLE) values ('Beef - Ground Lean Fresh');
insert into ORDENES (DETALLE) values ('Cape Capensis - Fillet');
insert into ORDENES (DETALLE) values ('Radish - Pickled');
insert into ORDENES (DETALLE) values ('Cheese - Cottage Cheese');
insert into ORDENES (DETALLE) values ('Strawberries');
insert into ORDENES (DETALLE) values ('Lobster - Base');
insert into ORDENES (DETALLE) values ('Lamb - Whole Head Off');
insert into ORDENES (DETALLE) values ('Melon - Watermelon, Seedless');
insert into ORDENES (DETALLE) values ('Ice Cream Bar - Rolo Cone');
insert into ORDENES (DETALLE) values ('Tea - English Breakfast');
insert into ORDENES (DETALLE) values ('Bread - Pita, Mini');
insert into ORDENES (DETALLE) values ('Bread - Frozen Basket Variety');
insert into ORDENES (DETALLE) values ('Pail - 15l White, With Handle');
insert into ORDENES (DETALLE) values ('Icecream - Dstk Strw Chseck');
insert into ORDENES (DETALLE) values ('Scallops - In Shell');
insert into ORDENES (DETALLE) values ('Pesto - Primerba, Paste');
insert into ORDENES (DETALLE) values ('Piping Jelly - All Colours');
insert into ORDENES (DETALLE) values ('Muffin Mix - Lemon Cranberry');
insert into ORDENES (DETALLE) values ('Trueblue - Blueberry Cranberry');
insert into ORDENES (DETALLE) values ('Nacho Chips');
insert into ORDENES (DETALLE) values ('Iced Tea - Lemon, 460 Ml');
insert into ORDENES (DETALLE) values ('Tea - Lemon Scented');
insert into ORDENES (DETALLE) values ('Mousse - Mango');
insert into ORDENES (DETALLE) values ('Bag Clear 10 Lb');
insert into ORDENES (DETALLE) values ('Yoghurt Tubes');
insert into ORDENES (DETALLE) values ('Lemonade - Mandarin, 591 Ml');
insert into ORDENES (DETALLE) values ('Mint - Fresh');
insert into ORDENES (DETALLE) values ('Wine - Marlbourough Sauv Blanc');
insert into ORDENES (DETALLE) values ('Mushroom - White Button');
insert into ORDENES (DETALLE) values ('Red Snapper - Fillet, Skin On');
insert into ORDENES (DETALLE) values ('Appetizer - Mini Egg Roll, Shrimp');
insert into ORDENES (DETALLE) values ('Beans - Fava, Canned');
insert into ORDENES (DETALLE) values ('Butter Sweet');
insert into ORDENES (DETALLE) values ('Sauerkraut');
insert into ORDENES (DETALLE) values ('Ham - Virginia');
insert into ORDENES (DETALLE) values ('Peas Snow');
insert into ORDENES (DETALLE) values ('Beef - Tongue, Cooked');
insert into ORDENES (DETALLE) values ('Pastry - Chocolate Marble Tea');
insert into ORDENES (DETALLE) values ('Wine - Chateau Aqueria Tavel');
insert into ORDENES (DETALLE) values ('Wine - Ruffino Chianti');
insert into ORDENES (DETALLE) values ('Wine - Magnotta - Bel Paese White');
insert into ORDENES (DETALLE) values ('Turkey - Breast, Double');
insert into ORDENES (DETALLE) values ('Wine - Beaujolais Villages');
insert into ORDENES (DETALLE) values ('Compound - Passion Fruit');
insert into ORDENES (DETALLE) values ('Horseradish Root');
insert into ORDENES (DETALLE) values ('Appetizer - Asian Shrimp Roll');
insert into ORDENES (DETALLE) values ('Coke - Classic, 355 Ml');
insert into ORDENES (DETALLE) values ('Pecan Raisin - Tarts');
insert into ORDENES (DETALLE) values ('Soup - Campbellschix Stew');
insert into ORDENES (DETALLE) values ('Bread - Italian Corn Meal Poly');
insert into ORDENES (DETALLE) values ('Kiwi Gold Zespri');
insert into ORDENES (DETALLE) values ('Goat - Leg');
insert into ORDENES (DETALLE) values ('Pastry - Baked Scones - Mini');
insert into ORDENES (DETALLE) values ('Port - 74 Brights');
insert into ORDENES (DETALLE) values ('Pail - 4l White, With Handle');
insert into ORDENES (DETALLE) values ('Pepper - White, Whole');
insert into ORDENES (DETALLE) values ('Wine - Merlot Vina Carmen');
insert into ORDENES (DETALLE) values ('Chilli Paste, Sambal Oelek');
insert into ORDENES (DETALLE) values ('Skirt - 29 Foot');
insert into ORDENES (DETALLE) values ('Juice - Clamato, 341 Ml');
insert into ORDENES (DETALLE) values ('Capon - Breast, Double, Wing On');
insert into ORDENES (DETALLE) values ('Cheese - Ricotta');
insert into ORDENES (DETALLE) values ('Sugar - Brown');
insert into ORDENES (DETALLE) values ('Orange - Canned, Mandarin');
insert into ORDENES (DETALLE) values ('Wine - Stoneliegh Sauvignon');
insert into ORDENES (DETALLE) values ('Sauce - Sesame Thai Dressing');
insert into ORDENES (DETALLE) values ('Wine - Riesling Alsace Ac 2001');
insert into ORDENES (DETALLE) values ('Fond - Neutral');
insert into ORDENES (DETALLE) values ('Coffee - French Vanilla Frothy');
insert into ORDENES (DETALLE) values ('Onions - Pearl');
insert into ORDENES (DETALLE) values ('Beef - Rib Roast, Cap On');
insert into ORDENES (DETALLE) values ('Beef - Rib Eye Aaa');
insert into ORDENES (DETALLE) values ('Juice - Ocean Spray Kiwi');
insert into ORDENES (DETALLE) values ('Vinegar - Tarragon');
insert into ORDENES (DETALLE) values ('Vermacelli - Sprinkles, Assorted');
insert into ORDENES (DETALLE) values ('Bread - Dark Rye');
insert into ORDENES (DETALLE) values ('Wine - White, Concha Y Toro');
insert into ORDENES (DETALLE) values ('Wine - White, Pelee Island');
insert into ORDENES (DETALLE) values ('Wine - Red, Cooking');
insert into ORDENES (DETALLE) values ('Steampan - Foil');
insert into ORDENES (DETALLE) values ('Tendrils - Baby Pea, Organic');
insert into ORDENES (DETALLE) values ('Brandy - Bar');
insert into ORDENES (DETALLE) values ('Beef - Prime Rib Aaa');
insert into ORDENES (DETALLE) values ('Cake - Bande Of Fruit');
insert into ORDENES (DETALLE) values ('Juice - Apple, 341 Ml');
insert into ORDENES (DETALLE) values ('Trueblue - Blueberry');
insert into ORDENES (DETALLE) values ('Ginger - Pickled');
insert into ORDENES (DETALLE) values ('Muffin - Banana Nut Individual');
insert into ORDENES (DETALLE) values ('Wine - Red, Metus Rose');
insert into ORDENES (DETALLE) values ('Sauce - Thousand Island');
insert into ORDENES (DETALLE) values ('Muffin - Bran Ind Wrpd');
insert into ORDENES (DETALLE) values ('Cookies - Englishbay Oatmeal');
insert into ORDENES (DETALLE) values ('Beef - Sushi Flat Iron Steak');
insert into ORDENES (DETALLE) values ('Wine - Zinfandel Rosenblum');
insert into ORDENES (DETALLE) values ('Sterno - Chafing Dish Fuel');
insert into ORDENES (DETALLE) values ('Flour - Pastry');
insert into ORDENES (DETALLE) values ('Fenngreek Seed');
insert into ORDENES (DETALLE) values ('Cheese - Mozzarella, Shredded');
insert into ORDENES (DETALLE) values ('Octopus - Baby, Cleaned');
insert into ORDENES (DETALLE) values ('Oil - Grapeseed Oil');
insert into ORDENES (DETALLE) values ('Beer - Fruli');
insert into ORDENES (DETALLE) values ('Oil - Avocado');
insert into ORDENES (DETALLE) values ('Chicken - Bones');
insert into ORDENES (DETALLE) values ('Lettuce - Escarole');
insert into ORDENES (DETALLE) values ('Turkey - Oven Roast Breast');
insert into ORDENES (DETALLE) values ('Cheese - Swiss');
insert into ORDENES (DETALLE) values ('Beef - Tongue, Fresh');
insert into ORDENES (DETALLE) values ('Table Cloth 53x69 White');
insert into ORDENES (DETALLE) values ('Flour - Semolina');
insert into ORDENES (DETALLE) values ('Bread - Rye');
insert into ORDENES (DETALLE) values ('Strawberries');
insert into ORDENES (DETALLE) values ('Sprouts - Onion');
insert into ORDENES (DETALLE) values ('Coconut - Creamed, Pure');
insert into ORDENES (DETALLE) values ('Soup - Beef, Base Mix');
insert into ORDENES (DETALLE) values ('Pastry - Butterscotch Baked');
insert into ORDENES (DETALLE) values ('Coffee - Hazelnut Cream');
insert into ORDENES (DETALLE) values ('Pickles - Gherkins');
insert into ORDENES (DETALLE) values ('Longos - Grilled Veg Sandwiches');
